import type { EventConfig, Handlers } from "motia";

export const config: EventConfig = {
  name: "Generate-Prompts",
  type: "event",
  description: "Generate prompts based on uploaded video",
  flows: ["yt.video.upload"],
  subscribes: ["file.uploaded"],
  emits: [
    { topic: "initial.title.generated", label: "Title Generated" },
    { topic: "thumbnail.prompts.generated", label: "Thumbnail Prompt Generated" },
    { topic: "initial.title.thumbnail.prompts.generation.error", label: "Generation Error", conditional: true },
  ],
};

export const handler: Handlers["Generate-Prompts"] = async (
  input: any,
  { emit, logger, state }: any
) => {
  const { traceId } = input;

  try {
    logger.info("Starting prompt generation", { traceId });

    // Get data from state
    const videoData = await state.get(traceId, "videoData");
    const metadata = await state.get(traceId, "metadata");

    if (!videoData || !metadata) {
      throw new Error("Video data or metadata not found in state");
    }

    // Update status to processing
    await state.set(traceId, "status", {
      status: "generating-prompts",
      updatedAt: new Date().toISOString(),
    });

    logger.info("Retrieved data from state", {
      traceId,
      fileName: videoData.fileName,
      hasTitle: Boolean(metadata.title),
      autoGenerateTitle: metadata.autoGenerateTitle,
      autoGenerateDescription: metadata.autoGenerateDescription,
    });

    // Build prompts based on metadata options
    const prompts: Record<string, string> = {};

    if (metadata.autoGenerateTitle) {
      prompts.titlePrompt = `Generate an engaging, SEO-optimized YouTube title for a video file named "${videoData.fileName}". 
The title should be catchy, under 100 characters, and encourage clicks.
${metadata.title ? `User provided context: ${metadata.title}` : ""}`;
    }

    if (metadata.autoGenerateDescription) {
      prompts.descriptionPrompt = `Generate a comprehensive YouTube description for a video file named "${videoData.fileName}".
Include relevant keywords, timestamps placeholder, and a call to action.
${metadata.description ? `User provided context: ${metadata.description}` : ""}
${metadata.tags?.length > 0 ? `Related tags: ${metadata.tags.join(", ")}` : ""}`;
    }

    prompts.thumbnailPrompt = `Generate an eye-catching YouTube thumbnail concept for a video titled "${metadata.title || videoData.fileName}".
Describe a visually striking image that would attract viewers.
Include suggested text overlay, colors, and composition.`;

    // Store prompts in state
    await state.set(traceId, "prompts", {
      ...prompts,
      generatedAt: new Date().toISOString(),
    });

    // Update status
    await state.set(traceId, "status", {
      status: "prompts-generated",
      updatedAt: new Date().toISOString(),
    });

    logger.info("Prompts generated successfully", {
      traceId,
      promptCount: Object.keys(prompts).length,
    });

    await emit({
      topic: "thumbnail.prompts.generated",
      data: {
        traceId,
        promptTypes: Object.keys(prompts),
      },
    });
  } catch (error: any) {
    logger.error("Error generating prompts", {
      traceId,
      error: error.message,
    });

    // Update status to failed
    await state.set(traceId, "status", {
      status: "prompt-generation-failed",
      error: error.message,
      updatedAt: new Date().toISOString(),
    });

    await emit({
      topic: "thumbnail.prompts.generation.error",
      data: {
        traceId,
        error: error.message,
      },
    });
  }
};
