import React, { useState, useEffect } from "react";

interface YouTubeChannel {
  channelId: string;
  channelName: string;
  avatarUrl?: string;
  subscriberCount?: number;
}

interface VideoUpload {
  traceId: string;
  title: string;
  description: string;
  status:
    | "pending"
    | "analyzing"
    | "generating_thumbnail"
    | "uploading_to_youtube"
    | "published"
    | "failed";
  thumbnailUrl?: string;
  youtubeVideoId?: string;
  youtubeVideoUrl?: string;
  createdAt: string;
  error?: string;
  progress?: number;
  currentStep?: string;
}

interface UploadFormData {
  title: string;
  description: string;
  tags: string;
  privacy: "public" | "unlisted" | "private";
  autoGenerateTitle: boolean;
  autoGenerateDescription: boolean;
}

interface WorkflowStep {
  id: string;
  label: string;
  status: "idle" | "processing" | "completed" | "failed";
}

// Add interface for stored tokens
interface StoredTokens {
  accessToken: string | null;
  refreshToken: string | null;
  email: string | null;
}

export function YTDashboardUI() {
  const [activeTab, setActiveTab] = useState<"upload" | "videos" | "settings">(
    "upload"
  );
  const [isConnected, setIsConnected] = useState(false);
  const [channel, setChannel] = useState<YouTubeChannel | null>(null);
  const [videos, setVideos] = useState<VideoUpload[]>([]);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [currentWorkflow, setCurrentWorkflow] = useState<VideoUpload | null>(
    null
  );
  const [workflowSteps, setWorkflowSteps] = useState<WorkflowStep[]>([
    { id: "upload", label: "Uploading Video", status: "idle" },
    { id: "analyze", label: "Analyzing Content (Gemini AI)", status: "idle" },
    { id: "thumbnail", label: "Generating Thumbnail", status: "idle" },
    { id: "youtube", label: "Publishing to YouTube", status: "idle" },
    { id: "complete", label: "Complete", status: "idle" },
  ]);
  const [formData, setFormData] = useState<UploadFormData>({
    title: "",
    description: "",
    tags: "",
    privacy: "private",
    autoGenerateTitle: true,
    autoGenerateDescription: true,
  });
  const [tokens, setTokens] = useState<StoredTokens>({
    accessToken: null,
    refreshToken: null,
    email: null,
  });

  const API_BASE = "http://localhost:3000";

  // Load tokens from localStorage on mount
  useEffect(() => {
    const storedTokens = {
      accessToken: localStorage.getItem("yt_access_token"),
      refreshToken: localStorage.getItem("yt_refresh_token"),
      email: localStorage.getItem("yt_email"),
    };
    setTokens(storedTokens);

    // If we have tokens, check connection status
    if (storedTokens.accessToken) {
      checkConnectionStatus();
    }

    fetchVideos();
  }, []);

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === "youtube-auth-success") {
        // Save tokens to localStorage
        if (event.data.accessToken) {
          localStorage.setItem("yt_access_token", event.data.accessToken);
        }
        if (event.data.refreshToken) {
          localStorage.setItem("yt_refresh_token", event.data.refreshToken);
        }
        if (event.data.email) {
          localStorage.setItem("yt_email", event.data.email);
        }

        // Update state
        setTokens({
          accessToken: event.data.accessToken || null,
          refreshToken: event.data.refreshToken || null,
          email: event.data.email || null,
        });

        checkConnectionStatus();
        setSuccess("YouTube channel connected successfully!");
        clearMessage();
      } else if (event.data?.type === "youtube-auth-error") {
        setError("Failed to connect YouTube channel");
        clearMessage();
      }
    };

    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, []);

  const clearMessage = () => {
    setTimeout(() => {
      setError("");
      setSuccess("");
    }, 5000);
  };

  const checkConnectionStatus = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/youtube/status`);
      const data = await res.json();
      setIsConnected(data.connected);
      if (data.channel) {
        setChannel(data.channel);
      }
    } catch {
      setIsConnected(false);
    }
  };

  const fetchVideos = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/youtube/videos`);
      const data = await res.json();
      setVideos(data.videos || []);
    } catch {
      console.error("Failed to fetch videos");
    }
  };

  const handleConnect = () => {
    window.open(
      `${API_BASE}/yt-channel-auth`,
      "YouTube Auth",
      "width=600,height=700,scrollbars=yes"
    );
  };

  const handleDisconnect = async () => {
    try {
      await fetch(`${API_BASE}/api/youtube/disconnect`, { method: "POST" });

      // Clear stored tokens
      localStorage.removeItem("yt_access_token");
      localStorage.removeItem("yt_refresh_token");
      localStorage.removeItem("yt_email");

      // Clear state
      setTokens({
        accessToken: null,
        refreshToken: null,
        email: null,
      });

      setIsConnected(false);
      setChannel(null);
      setSuccess("YouTube channel disconnected");
      clearMessage();
    } catch {
      setError("Failed to disconnect");
      clearMessage();
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const validFormats = [
        "video/mp4",
        "video/quicktime",
        "video/webm",
        "video/x-matroska",
      ];
      if (!validFormats.includes(file.type)) {
        setError("Invalid video format. Supported: MP4, MOV, WebM, MKV");
        clearMessage();
        return;
      }
      setSelectedFile(file);
      if (!formData.autoGenerateTitle && !formData.title) {
        setFormData((prev) => ({
          ...prev,
          title: file.name.replace(/\.[^.]+$/, ""),
        }));
      }
    }
  };

  const handleFileDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    const file = e.dataTransfer.files?.[0];
    if (file) {
      const validFormats = [
        "video/mp4",
        "video/quicktime",
        "video/webm",
        "video/x-matroska",
      ];
      if (!validFormats.includes(file.type)) {
        setError("Invalid video format. Supported: MP4, MOV, WebM, MKV");
        clearMessage();
        return;
      }
      setSelectedFile(file);
    }
  };

  const updateWorkflowStep = (
    stepId: string,
    status: WorkflowStep["status"]
  ) => {
    setWorkflowSteps((prev) =>
      prev.map((step) => (step.id === stepId ? { ...step, status } : step))
    );
  };

  const resetWorkflowSteps = () => {
    setWorkflowSteps((prev) =>
      prev.map((step) => ({ ...step, status: "idle" }))
    );
  };

  const handleUpload = async () => {
    if (!selectedFile) {
      setError("Please select a video file");
      clearMessage();
      return;
    }

    if (!formData.autoGenerateTitle && !formData.title.trim()) {
      setError("Please enter a title or enable auto-generate");
      clearMessage();
      return;
    }

    if (!isConnected) {
      setError("Please connect your YouTube channel first");
      clearMessage();
      return;
    }

    setUploading(true);
    setUploadProgress(0);
    setError("");
    resetWorkflowSteps();
    updateWorkflowStep("upload", "processing");

    try {
      const formPayload = new FormData();
      formPayload.append("video", selectedFile);
      formPayload.append("title", formData.title);
      formPayload.append("description", formData.description);
      formPayload.append("tags", formData.tags);
      formPayload.append("privacy", formData.privacy);
      formPayload.append(
        "autoGenerateTitle",
        String(formData.autoGenerateTitle)
      );
      formPayload.append(
        "autoGenerateDescription",
        String(formData.autoGenerateDescription)
      );

      const response = await uploadWithProgress(formPayload);

      if (response.success && response.traceId) {
        updateWorkflowStep("upload", "completed");
        setCurrentWorkflow({
          traceId: response.traceId,
          title: formData.title || "Processing...",
          description: formData.description,
          status: "analyzing",
          createdAt: new Date().toISOString(),
        });
        pollWorkflowStatus(response.traceId);
      } else {
        throw new Error(response.error || "Upload failed");
      }
    } catch (err) {
      updateWorkflowStep("upload", "failed");
      setError(err instanceof Error ? err.message : "Upload failed");
      clearMessage();
      setUploading(false);
    }
  };

  const uploadWithProgress = (
    formPayload: FormData
  ): Promise<{ success: boolean; traceId?: string; error?: string }> => {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();

      xhr.upload.addEventListener("progress", (e) => {
        if (e.lengthComputable) {
          const progress = Math.round((e.loaded / e.total) * 100);
          setUploadProgress(progress);
        }
      });

      xhr.addEventListener("load", () => {
        try {
          const response = JSON.parse(xhr.responseText);
          if (xhr.status === 200) {
            resolve({ success: true, traceId: response.traceId });
          } else {
            resolve({
              success: false,
              error: response.error || "Upload failed",
            });
          }
        } catch {
          resolve({ success: false, error: "Invalid response" });
        }
      });

      xhr.addEventListener("error", () => {
        reject(new Error("Network error"));
      });

      xhr.open("POST", `${API_BASE}/api/youtube/upload`);
      xhr.send(formPayload);
    });
  };

  const pollWorkflowStatus = async (traceId: string) => {
    let attempts = 0;
    const maxAttempts = 300; // 10 minutes max

    const poll = async () => {
      if (attempts >= maxAttempts) {
        updateWorkflowStep("complete", "failed");
        setError("Workflow timed out");
        setUploading(false);
        return;
      }
      attempts++;

      try {
        const res = await fetch(`${API_BASE}/api/youtube/video/${traceId}`);
        const data: VideoUpload = await res.json();

        setCurrentWorkflow(data);

        switch (data.status) {
          case "analyzing":
            updateWorkflowStep("analyze", "processing");
            break;
          case "generating_thumbnail":
            updateWorkflowStep("analyze", "completed");
            updateWorkflowStep("thumbnail", "processing");
            break;
          case "uploading_to_youtube":
            updateWorkflowStep("thumbnail", "completed");
            updateWorkflowStep("youtube", "processing");
            break;
          case "published":
            updateWorkflowStep("youtube", "completed");
            updateWorkflowStep("complete", "completed");
            setSuccess(`Video published successfully! ${data.youtubeVideoUrl}`);
            clearMessage();
            resetForm();
            fetchVideos();
            setUploading(false);
            return;
          case "failed":
            const failedStep = workflowSteps.find(
              (s) => s.status === "processing"
            );
            if (failedStep) updateWorkflowStep(failedStep.id, "failed");
            setError(`Publishing failed: ${data.error}`);
            clearMessage();
            setUploading(false);
            return;
        }

        setTimeout(poll, 2000);
      } catch {
        setTimeout(poll, 2000);
      }
    };

    poll();
  };

  const resetForm = () => {
    setSelectedFile(null);
    setFormData({
      title: "",
      description: "",
      tags: "",
      privacy: "private",
      autoGenerateTitle: true,
      autoGenerateDescription: true,
    });
    setUploadProgress(0);
    setCurrentWorkflow(null);
    resetWorkflowSteps();
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1024 * 1024 * 1024)
      return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
  };

  const getStatusBadge = (status: VideoUpload["status"]) => {
    const config: Record<
      VideoUpload["status"],
      { style: string; label: string }
    > = {
      pending: {
        style:
          "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300",
        label: "Pending",
      },
      analyzing: {
        style:
          "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300",
        label: "Analyzing",
      },
      generating_thumbnail: {
        style:
          "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300",
        label: "Generating Thumbnail",
      },
      uploading_to_youtube: {
        style:
          "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300",
        label: "Uploading to YouTube",
      },
      published: {
        style:
          "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300",
        label: "Published",
      },
      failed: {
        style: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300",
        label: "Failed",
      },
    };
    const { style, label } = config[status];
    return (
      <span className={`px-2 py-1 rounded-full text-xs font-medium ${style}`}>
        {label}
      </span>
    );
  };

  const getStepIcon = (status: WorkflowStep["status"]) => {
    switch (status) {
      case "idle":
        return "⚪";
      case "processing":
        return "🔄";
      case "completed":
        return "✅";
      case "failed":
        return "❌";
    }
  };

  return (
    <div className="flex flex-col h-full bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 border-b-2 border-red-500 p-6 shadow-sm">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white flex items-center gap-3">
              <span className="text-4xl">📺</span>
              YouTube Auto Publisher
            </h1>
            <p className="text-sm text-gray-600 dark:text-gray-400 mt-2 flex items-center gap-2">
              <span
                className={`inline-block w-2 h-2 rounded-full ${isConnected ? "bg-green-500 animate-pulse" : "bg-red-500"}`}
              />
              {isConnected
                ? `Connected to ${channel?.channelName || "YouTube"}`
                : "Not connected"}
            </p>
          </div>
          {isConnected && channel && (
            <div className="flex items-center gap-3">
              {channel.avatarUrl && (
                <img
                  src={channel.avatarUrl}
                  alt={channel.channelName}
                  className="w-12 h-12 rounded-full border-2 border-red-500"
                />
              )}
              <div className="text-right">
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {channel.channelName}
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  {channel.subscriberCount?.toLocaleString()} subscribers
                </p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Alerts */}
      {error && (
        <div className="mx-6 mt-4 p-4 bg-red-50 dark:bg-red-900/20 border-l-4 border-red-500 rounded-r-lg flex items-center gap-3">
          <span className="text-xl">❌</span>
          <p className="text-sm text-red-700 dark:text-red-300">{error}</p>
        </div>
      )}
      {success && (
        <div className="mx-6 mt-4 p-4 bg-green-50 dark:bg-green-900/20 border-l-4 border-green-500 rounded-r-lg flex items-center gap-3">
          <span className="text-xl">✅</span>
          <p className="text-sm text-green-700 dark:text-green-300">
            {success}
          </p>
        </div>
      )}

      {/* Tabs */}
      <div className="flex gap-1 border-b-2 border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 px-4 pt-2">
        {[
          { id: "upload", label: "Upload & Publish", icon: "🚀" },
          { id: "videos", label: "My Videos", icon: "🎬" },
          { id: "settings", label: "Settings", icon: "⚙️" },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as typeof activeTab)}
            className={`px-6 py-3 text-sm font-semibold transition-all rounded-t-lg ${
              activeTab === tab.id
                ? "bg-white dark:bg-gray-800 text-red-600 dark:text-red-400 border-b-2 border-red-500 -mb-0.5"
                : "text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200"
            }`}
          >
            <span className="flex items-center gap-2">
              {tab.icon} {tab.label}
            </span>
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-6">
        {/* Upload Tab */}
        {activeTab === "upload" && (
          <div className="max-w-5xl mx-auto">
            {!isConnected ? (
              <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-12 text-center">
                <div className="text-8xl mb-6">🔗</div>
                <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-3">
                  Connect Your YouTube Channel
                </h2>
                <p className="text-gray-600 dark:text-gray-400 mb-8 max-w-md mx-auto">
                  Connect your YouTube channel to automatically upload videos
                  with AI-generated thumbnails and titles
                </p>
                <button
                  onClick={handleConnect}
                  className="px-10 py-4 bg-red-600 text-white rounded-xl font-semibold hover:bg-red-700 transition-all shadow-lg text-lg"
                >
                  🔐 Connect with Google
                </button>
              </div>
            ) : (
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Upload Form */}
                <div className="lg:col-span-2 bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
                  <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 flex items-center gap-3">
                    <span className="text-3xl">📤</span> Upload Video
                  </h2>

                  {/* File Upload */}
                  <div className="mb-6">
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Video File *
                    </label>
                    <div
                      onDrop={handleFileDrop}
                      onDragOver={(e) => e.preventDefault()}
                      className={`border-2 border-dashed rounded-xl p-8 text-center transition-all cursor-pointer ${
                        selectedFile
                          ? "border-green-500 bg-green-50 dark:bg-green-900/20"
                          : "border-gray-300 dark:border-gray-600 hover:border-red-400 hover:bg-red-50 dark:hover:bg-red-900/10"
                      }`}
                    >
                      {selectedFile ? (
                        <div className="flex items-center justify-center gap-4">
                          <span className="text-5xl">🎥</span>
                          <div className="text-left">
                            <p className="font-medium text-gray-900 dark:text-white text-lg">
                              {selectedFile.name}
                            </p>
                            <p className="text-sm text-gray-500">
                              {formatFileSize(selectedFile.size)}
                            </p>
                          </div>
                          <button
                            onClick={() => setSelectedFile(null)}
                            className="ml-4 p-2 text-red-500 hover:bg-red-100 dark:hover:bg-red-900/30 rounded-full transition-all"
                          >
                            ✕
                          </button>
                        </div>
                      ) : (
                        <label className="cursor-pointer block">
                          <span className="text-6xl block mb-4">📁</span>
                          <p className="text-gray-600 dark:text-gray-400 mb-2 text-lg">
                            Drag and drop or click to select
                          </p>
                          <p className="text-xs text-gray-400">
                            MP4, MOV, WebM, MKV (max 128GB)
                          </p>
                          <input
                            type="file"
                            accept="video/mp4,video/quicktime,video/webm,video/x-matroska"
                            onChange={handleFileSelect}
                            className="hidden"
                          />
                        </label>
                      )}
                    </div>
                  </div>

                  {/* AI Options */}
                  <div className="mb-6 p-4 bg-purple-50 dark:bg-purple-900/20 rounded-xl border border-purple-200 dark:border-purple-800">
                    <h3 className="font-medium text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                      <span>🤖</span> AI Generation (Gemini)
                    </h3>
                    <div className="flex flex-wrap gap-4">
                      <label className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={formData.autoGenerateTitle}
                          onChange={(e) =>
                            setFormData((prev) => ({
                              ...prev,
                              autoGenerateTitle: e.target.checked,
                            }))
                          }
                          className="w-4 h-4 text-purple-600 rounded"
                        />
                        <span className="text-sm text-gray-700 dark:text-gray-300">
                          Auto-generate Title
                        </span>
                      </label>
                      <label className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={formData.autoGenerateDescription}
                          onChange={(e) =>
                            setFormData((prev) => ({
                              ...prev,
                              autoGenerateDescription: e.target.checked,
                            }))
                          }
                          className="w-4 h-4 text-purple-600 rounded"
                        />
                        <span className="text-sm text-gray-700 dark:text-gray-300">
                          Auto-generate Description
                        </span>
                      </label>
                      <span className="text-sm text-purple-600 dark:text-purple-400 flex items-center gap-1">
                        <span>🎨</span> Thumbnail always auto-generated
                      </span>
                    </div>
                  </div>

                  {/* Title */}
                  {!formData.autoGenerateTitle && (
                    <div className="mb-4">
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                        Title *
                      </label>
                      <input
                        type="text"
                        value={formData.title}
                        onChange={(e) =>
                          setFormData((prev) => ({
                            ...prev,
                            title: e.target.value,
                          }))
                        }
                        placeholder="Enter video title"
                        maxLength={100}
                        className="w-full px-4 py-3 border-2 border-gray-300 dark:border-gray-600 rounded-xl focus:ring-2 focus:ring-red-500 focus:border-red-500 bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      />
                      <p className="text-xs text-gray-400 mt-1">
                        {formData.title.length}/100
                      </p>
                    </div>
                  )}

                  {/* Description */}
                  {!formData.autoGenerateDescription && (
                    <div className="mb-4">
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                        Description
                      </label>
                      <textarea
                        value={formData.description}
                        onChange={(e) =>
                          setFormData((prev) => ({
                            ...prev,
                            description: e.target.value,
                          }))
                        }
                        placeholder="Enter video description"
                        rows={3}
                        maxLength={5000}
                        className="w-full px-4 py-3 border-2 border-gray-300 dark:border-gray-600 rounded-xl focus:ring-2 focus:ring-red-500 focus:border-red-500 bg-white dark:bg-gray-700 text-gray-900 dark:text-white resize-none"
                      />
                    </div>
                  )}

                  {/* Tags */}
                  <div className="mb-4">
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Tags (optional)
                    </label>
                    <input
                      type="text"
                      value={formData.tags}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          tags: e.target.value,
                        }))
                      }
                      placeholder="gaming, tutorial, vlog (comma separated)"
                      className="w-full px-4 py-3 border-2 border-gray-300 dark:border-gray-600 rounded-xl focus:ring-2 focus:ring-red-500 focus:border-red-500 bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    />
                  </div>

                  {/* Privacy */}
                  <div className="mb-6">
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Privacy
                    </label>
                    <div className="flex gap-3">
                      {[
                        { value: "private", label: "Private", icon: "🔒" },
                        { value: "unlisted", label: "Unlisted", icon: "🔗" },
                        { value: "public", label: "Public", icon: "🌍" },
                      ].map((option) => (
                        <button
                          key={option.value}
                          type="button"
                          onClick={() =>
                            setFormData((prev) => ({
                              ...prev,
                              privacy:
                                option.value as UploadFormData["privacy"],
                            }))
                          }
                          className={`flex-1 px-4 py-3 rounded-xl font-medium transition-all ${
                            formData.privacy === option.value
                              ? "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 border-2 border-red-500"
                              : "bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400 border-2 border-transparent hover:border-gray-300"
                          }`}
                        >
                          {option.icon} {option.label}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Upload Button */}
                  <button
                    onClick={handleUpload}
                    disabled={uploading || !selectedFile}
                    className="w-full px-8 py-4 bg-gradient-to-r from-red-600 to-red-700 text-white rounded-xl font-semibold hover:from-red-700 hover:to-red-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg text-lg"
                  >
                    {uploading ? (
                      <span className="flex items-center justify-center gap-3">
                        <svg
                          className="animate-spin h-6 w-6"
                          viewBox="0 0 24 24"
                        >
                          <circle
                            className="opacity-25"
                            cx="12"
                            cy="12"
                            r="10"
                            stroke="currentColor"
                            strokeWidth="4"
                            fill="none"
                          />
                          <path
                            className="opacity-75"
                            fill="currentColor"
                            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                          />
                        </svg>
                        Processing...
                      </span>
                    ) : (
                      <span className="flex items-center justify-center gap-2">
                        🚀 Upload & Auto-Publish
                      </span>
                    )}
                  </button>
                </div>

                {/* Workflow Progress */}
                <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
                  <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                    <span>📊</span> Workflow Progress
                  </h3>

                  {uploading && uploadProgress > 0 && uploadProgress < 100 && (
                    <div className="mb-6">
                      <div className="flex justify-between text-sm mb-2">
                        <span className="text-gray-600 dark:text-gray-400">
                          Uploading file...
                        </span>
                        <span className="text-gray-900 dark:text-white font-medium">
                          {uploadProgress}%
                        </span>
                      </div>
                      <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                        <div
                          className="bg-red-500 h-2 rounded-full transition-all duration-300"
                          style={{ width: `${uploadProgress}%` }}
                        />
                      </div>
                    </div>
                  )}

                  <div className="space-y-3">
                    {workflowSteps.map((step, index) => (
                      <div
                        key={step.id}
                        className={`flex items-center gap-3 p-3 rounded-lg transition-all ${
                          step.status === "processing"
                            ? "bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800"
                            : step.status === "completed"
                              ? "bg-green-50 dark:bg-green-900/20"
                              : step.status === "failed"
                                ? "bg-red-50 dark:bg-red-900/20"
                                : "bg-gray-50 dark:bg-gray-700/50"
                        }`}
                      >
                        <span
                          className={`text-xl ${step.status === "processing" ? "animate-spin" : ""}`}
                        >
                          {getStepIcon(step.status)}
                        </span>
                        <span
                          className={`text-sm font-medium ${
                            step.status === "processing"
                              ? "text-blue-700 dark:text-blue-300"
                              : step.status === "completed"
                                ? "text-green-700 dark:text-green-300"
                                : step.status === "failed"
                                  ? "text-red-700 dark:text-red-300"
                                  : "text-gray-500 dark:text-gray-400"
                          }`}
                        >
                          {step.label}
                        </span>
                      </div>
                    ))}
                  </div>

                  {currentWorkflow &&
                    currentWorkflow.status === "published" &&
                    currentWorkflow.youtubeVideoUrl && (
                      <div className="mt-6 p-4 bg-green-100 dark:bg-green-900/30 rounded-xl">
                        <p className="text-sm text-green-800 dark:text-green-300 mb-2 font-medium">
                          🎉 Published!
                        </p>
                        <a
                          href={currentWorkflow.youtubeVideoUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-sm text-green-700 dark:text-green-400 underline break-all"
                        >
                          {currentWorkflow.youtubeVideoUrl}
                        </a>
                      </div>
                    )}

                  {!uploading && !currentWorkflow && (
                    <div className="text-center py-8 text-gray-400">
                      <span className="text-4xl block mb-2">📋</span>
                      <p className="text-sm">Upload a video to see progress</p>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Videos Tab */}
        {activeTab === "videos" && (
          <div className="max-w-5xl mx-auto">
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-3">
                  <span className="text-3xl">🎬</span> My Videos
                </h2>
                <button
                  onClick={fetchVideos}
                  className="px-4 py-2 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-all flex items-center gap-2"
                >
                  🔄 Refresh
                </button>
              </div>

              {videos.length === 0 ? (
                <div className="text-center py-16">
                  <span className="text-8xl block mb-4">📭</span>
                  <p className="text-gray-600 dark:text-gray-400 text-lg">
                    No videos uploaded yet
                  </p>
                  <button
                    onClick={() => setActiveTab("upload")}
                    className="mt-4 px-6 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-all"
                  >
                    Upload your first video
                  </button>
                </div>
              ) : (
                <div className="space-y-4">
                  {videos.map((video) => (
                    <div
                      key={video.traceId}
                      className="flex items-center gap-4 p-4 border border-gray-200 dark:border-gray-700 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-all"
                    >
                      <div className="w-40 h-24 bg-gray-200 dark:bg-gray-700 rounded-lg flex items-center justify-center overflow-hidden flex-shrink-0">
                        {video.thumbnailUrl ? (
                          <img
                            src={video.thumbnailUrl}
                            alt={video.title}
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <span className="text-4xl">🎥</span>
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <h3 className="font-medium text-gray-900 dark:text-white truncate">
                          {video.title}
                        </h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                          {new Date(video.createdAt).toLocaleDateString()} •{" "}
                          {new Date(video.createdAt).toLocaleTimeString()}
                        </p>
                        {video.error && (
                          <p className="text-xs text-red-500 mt-1 truncate">
                            {video.error}
                          </p>
                        )}
                      </div>
                      <div className="flex items-center gap-3 flex-shrink-0">
                        {getStatusBadge(video.status)}
                        {video.youtubeVideoUrl && (
                          <a
                            href={video.youtubeVideoUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="px-4 py-2 bg-red-600 text-white rounded-lg text-sm hover:bg-red-700 transition-all flex items-center gap-1"
                          >
                            <span>▶️</span> Watch
                          </a>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Settings Tab */}
        {activeTab === "settings" && (
          <div className="max-w-3xl mx-auto space-y-6">
            {/* Connection */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 flex items-center gap-3">
                <span className="text-3xl">🔗</span> YouTube Connection
              </h2>

              <div className="p-6 border-2 border-gray-200 dark:border-gray-700 rounded-xl">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div
                      className={`w-14 h-14 rounded-full flex items-center justify-center text-2xl ${
                        isConnected
                          ? "bg-green-100 dark:bg-green-900/30"
                          : "bg-red-100 dark:bg-red-900/30"
                      }`}
                    >
                      {isConnected ? "✅" : "❌"}
                    </div>
                    <div>
                      <h3 className="font-semibold text-gray-900 dark:text-white text-lg">
                        {isConnected ? "Connected" : "Not Connected"}
                      </h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        {isConnected
                          ? channel?.channelName
                          : "Connect your channel to upload videos"}
                      </p>
                    </div>
                  </div>
                  {isConnected ? (
                    <button
                      onClick={handleDisconnect}
                      className="px-6 py-3 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-xl hover:bg-red-200 dark:hover:bg-red-900/50 transition-all font-medium"
                    >
                      Disconnect
                    </button>
                  ) : (
                    <button
                      onClick={handleConnect}
                      className="px-6 py-3 bg-red-600 text-white rounded-xl hover:bg-red-700 transition-all font-medium"
                    >
                      Connect
                    </button>
                  )}
                </div>
              </div>
            </div>

            {/* AI Info */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 flex items-center gap-3">
                <span className="text-3xl">🤖</span> AI Features
              </h2>

              <div className="space-y-4">
                <div className="p-4 bg-purple-50 dark:bg-purple-900/20 rounded-xl border border-purple-200 dark:border-purple-800">
                  <div className="flex items-start gap-4">
                    <span className="text-3xl">🎨</span>
                    <div>
                      <h3 className="font-semibold text-gray-900 dark:text-white">
                        Thumbnail Generation
                      </h3>
                      <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                        Gemini AI analyzes your video and generates an
                        eye-catching thumbnail optimized for YouTube (1280x720)
                      </p>
                    </div>
                  </div>
                </div>

                <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-200 dark:border-blue-800">
                  <div className="flex items-start gap-4">
                    <span className="text-3xl">📝</span>
                    <div>
                      <h3 className="font-semibold text-gray-900 dark:text-white">
                        Title & Description
                      </h3>
                      <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                        AI generates engaging titles and descriptions based on
                        your video content
                      </p>
                    </div>
                  </div>
                </div>

                <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-xl border border-green-200 dark:border-green-800">
                  <div className="flex items-start gap-4">
                    <span className="text-3xl">🏷️</span>
                    <div>
                      <h3 className="font-semibold text-gray-900 dark:text-white">
                        Smart Tags
                      </h3>
                      <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                        Automatically suggests relevant tags to improve
                        discoverability
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
