/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'WatchUploads': CronHandler<{ topic: 'file.new.detected'; data: never }>
    'ProcessNewFile': EventHandler<never, never>
    'ErrorHandler': EventHandler<never, never>
    'YouTube-OAuth-Callback': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'YouTube-Channel-Auth': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Upload-File': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'file.uploaded'; data: never } | { topic: 'file.upload.error'; data: never }>
    'Generate-Prompts': EventHandler<never, { topic: 'yt.prompts.generation.error'; data: never }>
  }
    
}