import { useState, useEffect } from "react";
import "./App.css";

interface YouTubeChannel {
  channelId: string;
  channelName: string;
  avatarUrl?: string;
  subscriberCount?: number;
}

interface VideoUpload {
  traceId: string;
  title: string;
  description: string;
  status:
    | "pending"
    | "analyzing"
    | "generating_thumbnail"
    | "uploading_to_youtube"
    | "published"
    | "failed";
  thumbnailUrl?: string;
  youtubeVideoId?: string;
  youtubeVideoUrl?: string;
  createdAt: string;
  error?: string;
}

interface UploadFormData {
  title: string;
  description: string;
  tags: string;
  privacy: "public" | "unlisted" | "private";
  autoGenerateTitle: boolean;
  autoGenerateDescription: boolean;
}

interface WorkflowStep {
  id: string;
  label: string;
  status: "idle" | "processing" | "completed" | "failed";
}

// Use Vite proxy - all /api requests will be proxied to backend
const API_BASE = import.meta.env.VITE_API_BASE_URL || "";

function App() {
  const [activeTab, setActiveTab] = useState<"upload" | "videos" | "settings">(
    "upload"
  );
  const [isConnected, setIsConnected] = useState(false);
  const [channel, setChannel] = useState<YouTubeChannel | null>(null);
  const [videos, setVideos] = useState<VideoUpload[]>([]);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [currentWorkflow, setCurrentWorkflow] = useState<VideoUpload | null>(
    null
  );
  const [workflowSteps, setWorkflowSteps] = useState<WorkflowStep[]>([
    { id: "upload", label: "Uploading Video", status: "idle" },
    { id: "analyze", label: "Analyzing Content (Gemini AI)", status: "idle" },
    { id: "thumbnail", label: "Generating Thumbnail", status: "idle" },
    { id: "youtube", label: "Publishing to YouTube", status: "idle" },
    { id: "complete", label: "Complete", status: "idle" },
  ]);
  const [formData, setFormData] = useState<UploadFormData>({
    title: "",
    description: "",
    tags: "",
    privacy: "private",
    autoGenerateTitle: true,
    autoGenerateDescription: true,
  });

  useEffect(() => {
    checkConnectionStatus();
    fetchVideos();
  }, []);

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === "youtube-auth-success") {
        if (event.data.accessToken) {
          localStorage.setItem("yt_access_token", event.data.accessToken);
        }
        if (event.data.refreshToken) {
          localStorage.setItem("yt_refresh_token", event.data.refreshToken);
        }
        if (event.data.email) {
          localStorage.setItem("yt_email", event.data.email);
        }

        checkConnectionStatus();
        setSuccess("YouTube channel connected successfully!");
        clearMessage();
      } else if (event.data?.type === "youtube-auth-error") {
        setError("Failed to connect YouTube channel");
        clearMessage();
      }
    };

    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, []);

  // Helper function to get stored tokens
  const getStoredTokens = () => {
    return {
      accessToken: localStorage.getItem("yt_access_token"),
      refreshToken: localStorage.getItem("yt_refresh_token"),
      email: localStorage.getItem("yt_email"),
    };
  };

  const clearMessage = () => {
    setTimeout(() => {
      setError("");
      setSuccess("");
    }, 5000);
  };

  const checkConnectionStatus = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/youtube/status`);
      const data = await res.json();
      setIsConnected(data.connected);
      if (data.channel) {
        setChannel(data.channel);
      }
    } catch {
      setIsConnected(false);
    }
  };

  const fetchVideos = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/youtube/videos`);
      const data = await res.json();
      setVideos(data.videos || []);
    } catch {
      console.error("Failed to fetch videos");
    }
  };

  const handleConnect = () => {
    const backendUrl =
      import.meta.env.VITE_API_BASE_URL || "http://localhost:3000";
    window.open(
      `${backendUrl}/yt-channel-auth`,
      "YouTube Auth",
      "width=600,height=700,scrollbars=yes"
    );
  };

  // Clear tokens on disconnect
  const handleDisconnect = async () => {
    try {
      await fetch(`${API_BASE}/api/youtube/disconnect`, { method: "POST" });

      // Clear stored tokens
      localStorage.removeItem("yt_access_token");
      localStorage.removeItem("yt_refresh_token");
      localStorage.removeItem("yt_email");

      setIsConnected(false);
      setChannel(null);
      setSuccess("YouTube channel disconnected");
      clearMessage();
    } catch {
      setError("Failed to disconnect");
      clearMessage();
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const validFormats = [
        "video/mp4",
        "video/quicktime",
        "video/webm",
        "video/x-matroska",
      ];
      if (!validFormats.includes(file.type)) {
        setError("Invalid video format. Supported: MP4, MOV, WebM, MKV");
        clearMessage();
        return;
      }
      setSelectedFile(file);
      if (!formData.autoGenerateTitle && !formData.title) {
        setFormData((prev) => ({
          ...prev,
          title: file.name.replace(/\.[^.]+$/, ""),
        }));
      }
    }
  };

  const handleFileDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    const file = e.dataTransfer.files?.[0];
    if (file) {
      const validFormats = [
        "video/mp4",
        "video/quicktime",
        "video/webm",
        "video/x-matroska",
      ];
      if (!validFormats.includes(file.type)) {
        setError("Invalid video format. Supported: MP4, MOV, WebM, MKV");
        clearMessage();
        return;
      }
      setSelectedFile(file);
    }
  };

  const updateWorkflowStep = (
    stepId: string,
    status: WorkflowStep["status"]
  ) => {
    setWorkflowSteps((prev) =>
      prev.map((step) => (step.id === stepId ? { ...step, status } : step))
    );
  };

  const resetWorkflowSteps = () => {
    setWorkflowSteps((prev) =>
      prev.map((step) => ({ ...step, status: "idle" }))
    );
  };

  const handleUpload = async () => {
    if (!selectedFile) {
      setError("Please select a video file");
      clearMessage();
      return;
    }

    if (!formData.autoGenerateTitle && !formData.title.trim()) {
      setError("Please enter a title or enable auto-generate");
      clearMessage();
      return;
    }

    if (!isConnected) {
      setError("Please connect your YouTube channel first");
      clearMessage();
      return;
    }

    setUploading(true);
    setUploadProgress(0);
    setError("");
    resetWorkflowSteps();
    updateWorkflowStep("upload", "processing");

    try {
      const formPayload = new FormData();
      formPayload.append("video", selectedFile);
      formPayload.append("title", formData.title);
      formPayload.append("description", formData.description);
      formPayload.append("tags", formData.tags);
      formPayload.append("privacy", formData.privacy);
      formPayload.append(
        "autoGenerateTitle",
        String(formData.autoGenerateTitle)
      );
      formPayload.append(
        "autoGenerateDescription",
        String(formData.autoGenerateDescription)
      );

      const response = await uploadWithProgress(formPayload);

      if (response.success && response.traceId) {
        updateWorkflowStep("upload", "completed");
        setCurrentWorkflow({
          traceId: response.traceId,
          title: formData.title || "Processing...",
          description: formData.description,
          status: "analyzing",
          createdAt: new Date().toISOString(),
        });
        pollWorkflowStatus(response.traceId);
      } else {
        throw new Error(response.error || "Upload failed");
      }
    } catch (err) {
      updateWorkflowStep("upload", "failed");
      setError(err instanceof Error ? err.message : "Upload failed");
      clearMessage();
      setUploading(false);
    }
  };

  const uploadWithProgress = (
    formPayload: FormData
  ): Promise<{ success: boolean; traceId?: string; error?: string }> => {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();

      xhr.upload.addEventListener("progress", (e) => {
        if (e.lengthComputable) {
          const progress = Math.round((e.loaded / e.total) * 100);
          setUploadProgress(progress);
        }
      });

      xhr.addEventListener("load", () => {
        try {
          const response = JSON.parse(xhr.responseText);
          if (xhr.status === 200) {
            resolve({ success: true, traceId: response.traceId });
          } else {
            resolve({
              success: false,
              error: response.error || "Upload failed",
            });
          }
        } catch {
          resolve({ success: false, error: "Invalid response" });
        }
      });

      xhr.addEventListener("error", () => {
        reject(new Error("Network error"));
      });

      xhr.open("POST", `${API_BASE}/api/youtube/upload`);
      xhr.send(formPayload);
    });
  };

  const pollWorkflowStatus = async (traceId: string) => {
    let attempts = 0;
    const maxAttempts = 300;

    const poll = async () => {
      if (attempts >= maxAttempts) {
        updateWorkflowStep("complete", "failed");
        setError("Workflow timed out");
        setUploading(false);
        return;
      }
      attempts++;

      try {
        const res = await fetch(`${API_BASE}/api/youtube/video/${traceId}`);
        const data: VideoUpload = await res.json();

        setCurrentWorkflow(data);

        switch (data.status) {
          case "analyzing":
            updateWorkflowStep("analyze", "processing");
            break;
          case "generating_thumbnail":
            updateWorkflowStep("analyze", "completed");
            updateWorkflowStep("thumbnail", "processing");
            break;
          case "uploading_to_youtube":
            updateWorkflowStep("thumbnail", "completed");
            updateWorkflowStep("youtube", "processing");
            break;
          case "published":
            updateWorkflowStep("youtube", "completed");
            updateWorkflowStep("complete", "completed");
            setSuccess(`Video published successfully! ${data.youtubeVideoUrl}`);
            clearMessage();
            resetForm();
            fetchVideos();
            setUploading(false);
            return;
          case "failed":
            const failedStep = workflowSteps.find(
              (s) => s.status === "processing"
            );
            if (failedStep) updateWorkflowStep(failedStep.id, "failed");
            setError(`Publishing failed: ${data.error}`);
            clearMessage();
            setUploading(false);
            return;
        }

        setTimeout(poll, 2000);
      } catch {
        setTimeout(poll, 2000);
      }
    };

    poll();
  };

  const resetForm = () => {
    setSelectedFile(null);
    setFormData({
      title: "",
      description: "",
      tags: "",
      privacy: "private",
      autoGenerateTitle: true,
      autoGenerateDescription: true,
    });
    setUploadProgress(0);
    setCurrentWorkflow(null);
    resetWorkflowSteps();
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1024 * 1024 * 1024)
      return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
  };

  const getStatusBadge = (status: VideoUpload["status"]) => {
    const config: Record<
      VideoUpload["status"],
      { className: string; label: string }
    > = {
      pending: { className: "badge badge-warning", label: "Pending" },
      analyzing: { className: "badge badge-info", label: "Analyzing" },
      generating_thumbnail: {
        className: "badge badge-purple",
        label: "Generating Thumbnail",
      },
      uploading_to_youtube: {
        className: "badge badge-orange",
        label: "Uploading to YouTube",
      },
      published: { className: "badge badge-success", label: "Published" },
      failed: { className: "badge badge-error", label: "Failed" },
    };
    const { className, label } = config[status];
    return <span className={className}>{label}</span>;
  };

  const getStepIcon = (status: WorkflowStep["status"]) => {
    switch (status) {
      case "idle":
        return <span className="step-icon idle">○</span>;
      case "processing":
        return <span className="step-icon processing">◐</span>;
      case "completed":
        return <span className="step-icon completed">✓</span>;
      case "failed":
        return <span className="step-icon failed">✕</span>;
    }
  };

  return (
    <div className="app">
      {/* Header */}
      <header className="header">
        <div className="header-content">
          <div className="header-left">
            <div className="logo">
              <svg
                className="logo-icon"
                viewBox="0 0 24 24"
                fill="currentColor"
              >
                <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z" />
              </svg>
              <h1>YouTube Auto Publisher</h1>
            </div>
            <div className="connection-status">
              <span
                className={`status-dot ${
                  isConnected ? "connected" : "disconnected"
                }`}
              ></span>
              <span className="status-text">
                {isConnected
                  ? `Connected to ${channel?.channelName || "YouTube"}`
                  : "Not connected"}
              </span>
            </div>
          </div>
          {isConnected && channel && (
            <div className="header-right">
              {channel.avatarUrl && (
                <img
                  src={channel.avatarUrl}
                  alt={channel.channelName}
                  className="channel-avatar"
                />
              )}
              <div className="channel-info">
                <span className="channel-name">{channel.channelName}</span>
                <span className="subscriber-count">
                  {channel.subscriberCount?.toLocaleString()} subscribers
                </span>
              </div>
            </div>
          )}
        </div>
      </header>

      {/* Alerts */}
      {error && (
        <div className="alert alert-error">
          <svg
            className="alert-icon"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="15" y1="9" x2="9" y2="15" />
            <line x1="9" y1="9" x2="15" y2="15" />
          </svg>
          <span>{error}</span>
        </div>
      )}
      {success && (
        <div className="alert alert-success">
          <svg
            className="alert-icon"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
          >
            <circle cx="12" cy="12" r="10" />
            <path d="M9 12l2 2 4-4" />
          </svg>
          <span>{success}</span>
        </div>
      )}

      {/* Navigation Tabs */}
      <nav className="tabs">
        <div className="tabs-container">
          {[
            {
              id: "upload",
              label: "Upload & Publish",
              icon: "M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12",
            },
            {
              id: "videos",
              label: "My Videos",
              icon: "M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z",
            },
            {
              id: "settings",
              label: "Settings",
              icon: "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z",
            },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as typeof activeTab)}
              className={`tab ${activeTab === tab.id ? "active" : ""}`}
            >
              <svg
                className="tab-icon"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d={tab.icon} />
              </svg>
              <span>{tab.label}</span>
            </button>
          ))}
        </div>
      </nav>

      {/* Main Content */}
      <main className="main">
        {/* Upload Tab */}
        {activeTab === "upload" && (
          <div className="upload-container">
            {!isConnected ? (
              <div className="connect-card">
                <div className="connect-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
                    />
                  </svg>
                </div>
                <h2>Connect Your YouTube Channel</h2>
                <p>
                  Connect your YouTube channel to automatically upload videos
                  with AI-generated thumbnails and titles
                </p>
                <button
                  onClick={handleConnect}
                  className="btn btn-primary btn-lg"
                >
                  <svg
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="btn-icon"
                  >
                    <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                    <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                    <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                    <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                  </svg>
                  Connect with Google
                </button>
              </div>
            ) : (
              <div className="upload-grid">
                {/* Upload Form */}
                <div className="card upload-form-card">
                  <div className="card-header">
                    <svg
                      className="card-icon"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"
                      />
                    </svg>
                    <h2>Upload Video</h2>
                  </div>

                  {/* File Upload Zone */}
                  <div
                    onDrop={handleFileDrop}
                    onDragOver={(e) => e.preventDefault()}
                    className={`dropzone ${selectedFile ? "has-file" : ""}`}
                  >
                    {selectedFile ? (
                      <div className="file-preview">
                        <div className="file-icon">
                          <svg
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
                            />
                          </svg>
                        </div>
                        <div className="file-info">
                          <span className="file-name">{selectedFile.name}</span>
                          <span className="file-size">
                            {formatFileSize(selectedFile.size)}
                          </span>
                        </div>
                        <button
                          onClick={() => setSelectedFile(null)}
                          className="file-remove"
                        >
                          <svg
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M6 18L18 6M6 6l12 12"
                            />
                          </svg>
                        </button>
                      </div>
                    ) : (
                      <label className="dropzone-content">
                        <div className="dropzone-icon">
                          <svg
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="1.5"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M12 16.5V9.75m0 0l3 3m-3-3l-3 3M6.75 19.5a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z"
                            />
                          </svg>
                        </div>
                        <span className="dropzone-title">
                          Drop your video here or click to browse
                        </span>
                        <span className="dropzone-hint">
                          MP4, MOV, WebM, MKV • Max 128GB
                        </span>
                        <input
                          type="file"
                          accept="video/mp4,video/quicktime,video/webm,video/x-matroska"
                          onChange={handleFileSelect}
                          className="dropzone-input"
                        />
                      </label>
                    )}
                  </div>

                  {/* AI Options */}
                  <div className="ai-options">
                    <div className="ai-options-header">
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z"
                        />
                      </svg>
                      <span>AI Generation (Gemini)</span>
                    </div>
                    <div className="ai-options-content">
                      <label className="checkbox-label">
                        <input
                          type="checkbox"
                          checked={formData.autoGenerateTitle}
                          onChange={(e) =>
                            setFormData((prev) => ({
                              ...prev,
                              autoGenerateTitle: e.target.checked,
                            }))
                          }
                        />
                        <span>Auto-generate Title</span>
                      </label>
                      <label className="checkbox-label">
                        <input
                          type="checkbox"
                          checked={formData.autoGenerateDescription}
                          onChange={(e) =>
                            setFormData((prev) => ({
                              ...prev,
                              autoGenerateDescription: e.target.checked,
                            }))
                          }
                        />
                        <span>Auto-generate Description</span>
                      </label>
                      <span className="ai-badge">
                        <svg
                          viewBox="0 0 24 24"
                          fill="currentColor"
                          className="ai-badge-icon"
                        >
                          <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z" />
                        </svg>
                        Thumbnail always auto-generated
                      </span>
                    </div>
                  </div>

                  {/* Title Input */}
                  {!formData.autoGenerateTitle && (
                    <div className="form-group">
                      <label className="form-label">Title *</label>
                      <input
                        type="text"
                        value={formData.title}
                        onChange={(e) =>
                          setFormData((prev) => ({
                            ...prev,
                            title: e.target.value,
                          }))
                        }
                        placeholder="Enter video title"
                        maxLength={100}
                        className="form-input"
                      />
                      <span className="form-hint">
                        {formData.title.length}/100
                      </span>
                    </div>
                  )}

                  {/* Description Input */}
                  {!formData.autoGenerateDescription && (
                    <div className="form-group">
                      <label className="form-label">Description</label>
                      <textarea
                        value={formData.description}
                        onChange={(e) =>
                          setFormData((prev) => ({
                            ...prev,
                            description: e.target.value,
                          }))
                        }
                        placeholder="Enter video description"
                        rows={3}
                        maxLength={5000}
                        className="form-textarea"
                      />
                    </div>
                  )}

                  {/* Tags Input */}
                  <div className="form-group">
                    <label className="form-label">Tags (optional)</label>
                    <input
                      type="text"
                      value={formData.tags}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          tags: e.target.value,
                        }))
                      }
                      placeholder="gaming, tutorial, vlog (comma separated)"
                      className="form-input"
                    />
                  </div>

                  {/* Privacy Options */}
                  <div className="form-group">
                    <label className="form-label">Privacy</label>
                    <div className="privacy-options">
                      {[
                        {
                          value: "private",
                          label: "Private",
                          icon: "M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z",
                        },
                        {
                          value: "unlisted",
                          label: "Unlisted",
                          icon: "M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1",
                        },
                        {
                          value: "public",
                          label: "Public",
                          icon: "M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
                        },
                      ].map((option) => (
                        <button
                          key={option.value}
                          type="button"
                          onClick={() =>
                            setFormData((prev) => ({
                              ...prev,
                              privacy:
                                option.value as UploadFormData["privacy"],
                            }))
                          }
                          className={`privacy-option ${
                            formData.privacy === option.value ? "selected" : ""
                          }`}
                        >
                          <svg
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <path d={option.icon} />
                          </svg>
                          <span>{option.label}</span>
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Upload Button */}
                  <button
                    onClick={handleUpload}
                    disabled={uploading || !selectedFile}
                    className="btn btn-primary btn-block"
                  >
                    {uploading ? (
                      <>
                        <svg className="btn-spinner" viewBox="0 0 24 24">
                          <circle
                            className="spinner-track"
                            cx="12"
                            cy="12"
                            r="10"
                            fill="none"
                            strokeWidth="3"
                          />
                          <circle
                            className="spinner-head"
                            cx="12"
                            cy="12"
                            r="10"
                            fill="none"
                            strokeWidth="3"
                          />
                        </svg>
                        <span>Processing...</span>
                      </>
                    ) : (
                      <>
                        <svg
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          className="btn-icon"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M15.59 14.37a6 6 0 01-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 006.16-12.12A14.98 14.98 0 009.631 8.41m5.96 5.96a14.926 14.926 0 01-5.841 2.58m-.119-8.54a6 6 0 00-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 00-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 01-2.448-2.448 14.9 14.9 0 01.06-.312m-2.24 2.39a4.493 4.493 0 00-1.757 4.306 4.493 4.493 0 004.306-1.758M16.5 9a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z"
                          />
                        </svg>
                        <span>Upload & Auto-Publish</span>
                      </>
                    )}
                  </button>
                </div>

                {/* Workflow Progress */}
                <div className="card workflow-card">
                  <div className="card-header">
                    <svg
                      className="card-icon"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z"
                      />
                    </svg>
                    <h2>Workflow Progress</h2>
                  </div>

                  {uploading && uploadProgress > 0 && uploadProgress < 100 && (
                    <div className="progress-section">
                      <div className="progress-header">
                        <span>Uploading file...</span>
                        <span>{uploadProgress}%</span>
                      </div>
                      <div className="progress-bar">
                        <div
                          className="progress-fill"
                          style={{ width: `${uploadProgress}%` }}
                        />
                      </div>
                    </div>
                  )}

                  <div className="workflow-steps">
                    {workflowSteps.map((step) => (
                      <div
                        key={step.id}
                        className={`workflow-step ${step.status}`}
                      >
                        {getStepIcon(step.status)}
                        <span className="step-label">{step.label}</span>
                      </div>
                    ))}
                  </div>

                  {currentWorkflow?.status === "published" &&
                    currentWorkflow.youtubeVideoUrl && (
                      <div className="success-result">
                        <div className="success-icon">🎉</div>
                        <span className="success-title">Published!</span>
                        <a
                          href={currentWorkflow.youtubeVideoUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="success-link"
                        >
                          {currentWorkflow.youtubeVideoUrl}
                        </a>
                      </div>
                    )}

                  {!uploading && !currentWorkflow && (
                    <div className="workflow-empty">
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="1.5"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"
                        />
                      </svg>
                      <span>Upload a video to see progress</span>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Videos Tab */}
        {activeTab === "videos" && (
          <div className="card">
            <div className="card-header with-action">
              <div className="card-title">
                <svg
                  className="card-icon"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
                <h2>My Videos</h2>
              </div>
              <button
                onClick={fetchVideos}
                className="btn btn-secondary btn-sm"
              >
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  className="btn-icon"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99"
                  />
                </svg>
                Refresh
              </button>
            </div>

            {videos.length === 0 ? (
              <div className="empty-state">
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M2.25 13.5h3.86a2.25 2.25 0 012.012 1.244l.256.512a2.25 2.25 0 002.013 1.244h3.218a2.25 2.25 0 002.013-1.244l.256-.512a2.25 2.25 0 012.013-1.244h3.859m-19.5.338V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18v-4.162c0-.224-.034-.447-.1-.661L19.24 5.338a2.25 2.25 0 00-2.15-1.588H6.911a2.25 2.25 0 00-2.15 1.588L2.35 13.177a2.25 2.25 0 00-.1.661z"
                  />
                </svg>
                <h3>No videos uploaded yet</h3>
                <p>Upload your first video to get started</p>
                <button
                  onClick={() => setActiveTab("upload")}
                  className="btn btn-primary"
                >
                  Upload Video
                </button>
              </div>
            ) : (
              <div className="video-list">
                {videos.map((video) => (
                  <div key={video.traceId} className="video-item">
                    <div className="video-thumbnail">
                      {video.thumbnailUrl ? (
                        <img src={video.thumbnailUrl} alt={video.title} />
                      ) : (
                        <div className="thumbnail-placeholder">
                          <svg
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="1.5"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
                            />
                          </svg>
                        </div>
                      )}
                    </div>
                    <div className="video-info">
                      <h3 className="video-title">{video.title}</h3>
                      <span className="video-date">
                        {new Date(video.createdAt).toLocaleDateString()} •{" "}
                        {new Date(video.createdAt).toLocaleTimeString()}
                      </span>
                      {video.error && (
                        <span className="video-error">{video.error}</span>
                      )}
                    </div>
                    <div className="video-actions">
                      {getStatusBadge(video.status)}
                      {video.youtubeVideoUrl && (
                        <a
                          href={video.youtubeVideoUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="btn btn-primary btn-sm"
                        >
                          <svg
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="btn-icon"
                          >
                            <path d="M8 5v14l11-7z" />
                          </svg>
                          Watch
                        </a>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Settings Tab */}
        {activeTab === "settings" && (
          <div className="settings-container">
            {/* Connection Card */}
            <div className="card">
              <div className="card-header">
                <svg
                  className="card-icon"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
                  />
                </svg>
                <h2>YouTube Connection</h2>
              </div>

              <div className="connection-card-content">
                <div className="connection-info">
                  <div
                    className={`connection-icon ${
                      isConnected ? "connected" : "disconnected"
                    }`}
                  >
                    {isConnected ? (
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                        />
                      </svg>
                    ) : (
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
                        />
                      </svg>
                    )}
                  </div>
                  <div className="connection-details">
                    <h3>{isConnected ? "Connected" : "Not Connected"}</h3>
                    <p>
                      {isConnected
                        ? channel?.channelName
                        : "Connect your channel to upload videos"}
                    </p>
                  </div>
                </div>
                {isConnected ? (
                  <button onClick={handleDisconnect} className="btn btn-danger">
                    Disconnect
                  </button>
                ) : (
                  <button onClick={handleConnect} className="btn btn-primary">
                    Connect
                  </button>
                )}
              </div>
            </div>

            {/* AI Features Card */}
            <div className="card">
              <div className="card-header">
                <svg
                  className="card-icon"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z"
                  />
                </svg>
                <h2>AI Features</h2>
              </div>

              <div className="feature-list">
                <div className="feature-item purple">
                  <div className="feature-icon">
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
                      />
                    </svg>
                  </div>
                  <div className="feature-content">
                    <h3>Thumbnail Generation</h3>
                    <p>
                      Gemini AI analyzes your video and generates an
                      eye-catching thumbnail optimized for YouTube (1280x720)
                    </p>
                  </div>
                </div>

                <div className="feature-item blue">
                  <div className="feature-icon">
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"
                      />
                    </svg>
                  </div>
                  <div className="feature-content">
                    <h3>Title & Description</h3>
                    <p>
                      AI generates engaging titles and descriptions based on
                      your video content
                    </p>
                  </div>
                </div>

                <div className="feature-item green">
                  <div className="feature-icon">
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z"
                      />
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M6 6h.008v.008H6V6z"
                      />
                    </svg>
                  </div>
                  <div className="feature-content">
                    <h3>Smart Tags</h3>
                    <p>
                      Automatically suggests relevant tags to improve
                      discoverability
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
